In [1]:
import numpy as np
np.random.seed(42)


In [5]:
def celsius_to_fahrenheit(celsius_array):
    return celsius_array * 9 / 5 + 32
 
def filter_high_value(transactions, threshold=50000):
    return transactions[transactions >= threshold]
 
def reshape_to_days(readings):
    return readings.reshape(7, 24)
 
def daily_min_max(daily_readings):
    return daily_readings.min(axis=1), daily_readings.max(axis=1)
 

In [7]:
def total_revenue_by_product(units_sold, unit_price):
    # total units per product (sum over days), times price per product
    return units_sold.sum(axis=0) * unit_price
 
def weighted_final_scores(scores, weights):
    return scores @ weights
 
def solve_ingredient_costs():
    # 2f + 1s = 3000 ; 1f + 3s = 4000
    A = np.array([[2, 1], [1, 3]])
    b = np.array([3000, 4000])
    return np.linalg.solve(A, b)
 

In [9]:
def simulate_coin_flips(n_flips=50000, seed=42):
    np.random.seed(seed)
    return np.random.randint(0, 2, size=n_flips).mean()
 
def pct_waiting_over_7min(n_customers=10000, seed=42):
    np.random.seed(seed)
    waits = np.random.normal(5, 1.5, n_customers)
    return (waits > 7).mean() * 100
 
def simulate_portfolio_growth(start_value=1_000_000, n_days=252, seed=42):
    np.random.seed(seed)
    returns = np.random.normal(0.0005, 0.015, n_days)
    return start_value * np.cumprod(1 + returns)[-1]
 

In [11]:
def monte_carlo_portfolio(n_simulations=1000, start_value=1_000_000, n_days=252, seed=42):
    np.random.seed(seed)
    returns = np.random.normal(0.0005, 0.015, size=(n_simulations, n_days))
    prices = start_value * np.cumprod(1 + returns, axis=1)   # (1000, 252)
    final = prices[:, -1]
    return final.mean(), (final < start_value).mean() * 100
 
if __name__ == "__main__":
    print(celsius_to_fahrenheit(np.array([0, 20, 37, 100])))
    print(filter_high_value(np.array([12000, 55000, 49999, 100000, 50000])))
    r = reshape_to_days(np.arange(168)); print(r.shape, r[0])
    print(daily_min_max(r))
    print(total_revenue_by_product(np.array([[10,5],[8,6],[12,4]]), np.array([1000,2000])))
    print(weighted_final_scores(np.array([[90,80,70],[60,70,80],[100,90,95]]), np.array([0.5,0.3,0.2])))
    print(solve_ingredient_costs())
    print(simulate_coin_flips(), pct_waiting_over_7min(), simulate_portfolio_growth())
    print(monte_carlo_portfolio())

[ 32.   68.   98.6 212. ]
[ 55000 100000  50000]
(7, 24) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(array([  0,  24,  48,  72,  96, 120, 144]), array([ 23,  47,  71,  95, 119, 143, 167]))
[30000 30000]
[83. 67. 96.]
[1000. 1000.]
0.49908 9.229999999999999 1089172.0041520006
(1133520.334959366, 33.4)
